name: Deploy Qwik App On Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Qwik dependencies
        run: npm install

      - name: Build Qwik app
        run: npm run build

      - name: Deploy Qwik app to GitHub Pages
        uses: actions/github-script@v6
        with:
          script: |
            github.actions.checkout('main');
            github.actions.github.setDeployToken('${{ secrets.GITHUB_TOKEN }}');
            github.actions.github.run('gh-pages', {
              args: ['--push'],
              cwd: './build'
            });