name: Deploy App - GitHub Pages
on:
  push:
    branches: [pages/main, main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build and Push App to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install npm dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      # To allow routing in an Angular app deployed to GitHub Pages, we need to create a 404.html file in the build directory that is a copy of index.html
      # https://angular.io/guide/deployment#fallback-configuration-examples
      - name: Create 404.html build for routing in GitHub Pages
        run: cp "./dist/index.html" "./dist/404.html"

      # We're using v2 of the action "upload-page-artifact" because v3 is currently not working with GHES (GitHub Enterprise Server)
      - name: Upload artifact 
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: './dist'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2